__default__:
  memory: "{resources.mem_mb}"
  n: 1
  name: "{rule}.{wildcards}"
  queue: short
  outfile: "{log}"
run_kruskal_wallis:
  queue: bigmem
bwa_mem2_mem:
  n: "{threads}"
#create_ped:
#  queue: bigmem
