####################
# Locations
####################
rawdir:
    /hps/nobackup/birney/users/ian/MIKK_all
workdir:
    /hps/nobackup/birney/users/ian/MIKK_HMM
tmpdir:
    /hps/nobackup/birney/users/ian/tmp
google_drive_dir:
    # NOTE: you need to set up this (or some other) drive with `rclone config` first
    EBI_Google_Drive:pilot_paper/figs
mikk_vcf:
    /nfs/research/birney/projects/indigene/datafreeze/14-03-2019/vcf/medaka_inbred_panel_ensembl_new_reference_release_94.vcf.gz
sequence_dir:
    /nfs/research/birney/projects/indigene/raw_data/genecore/ian_behaviour
runs:
    - AAAMKYVHV
    - AAAN233HV
####################
# Parameters
####################
ref:
    # ensembl species name
    species: oryzias_latipes
    # ensembl release
    release: 104
    # genome build
    build: ASM223467v1
datasets:
    - F0
    - F2
    - Kiyosu_CC
seconds_interval:
    - 0.05
    - 0.08
    - 0.1
    - 0.15
    - 0.2
    - 0.3
    - 0.5
    - 1
hmm_variables:
    dist_angle:
        - distance
        - angle
n_states:
    - 5
    - 10
    - 12
    - 14
    - 15
    - 16
    - 17
    - 18
    - 20
####################
# Containers
####################
bash:
    docker://bash:5.1.12
opencv:
    /hps/nobackup/birney/users/ian/containers/pilot_paper/opencv_4.5.1.sif
ffmpeg:
    docker://jrottenberg/ffmpeg:4.4-ubuntu
idtrackerai:
    # NOTE: Dockerfile for this container: workflow/envs/idtrackerai/Dockerfile
    docker://saulpierottiebi/idtrackerai_cpu_gui:latest
rocker_tidyverse:
    docker://rocker/tidyverse:4.1.2
hmmlearn:
    /hps/nobackup/birney/users/ian/containers/pilot_paper/hmmlearn_0.2.7.sif
# Instructions on building container in config/init.sh
R:
    /hps/nobackup/birney/users/ian/containers/pilot_paper/R_4.1.2.sif
R_4.2.0:
    /hps/nobackup/birney/users/ian/containers/MIKK_HMM/R_4.2.0.sif
hmmlearn:
    /hps/nobackup/birney/users/ian/containers/pilot_paper/hmmlearn_0.2.7.sif
bwa-mem2:
    docker://quay.io/biocontainers/bwa-mem2:2.2.1--he513fc3_0
samtools:
    docker://quay.io/biocontainers/samtools:1.13--h8c37831_0
picard:
    docker://quay.io/biocontainers/picard:2.9.2--2